// Lesson catalog — Data Infrastructure: An IC5 System Design Field Guide
window.TRACKS = [
  { id: 'foundations', label: '01 · foundations', title: 'How to think about data systems.',
    hint: 'The mental model, the constraints (CAP / PACELC), the modeling decision tree. Everything downstream is downstream of these three.' },
  { id: 'storage', label: '02 · storage', title: 'Bytes on disk, queryable at scale.',
    hint: 'Row vs columnar, Parquet internals, the lakehouse table-format wars, partitioning that actually prunes.' },
  { id: 'movement', label: '03 · movement', title: 'Bytes in motion, batch and stream.',
    hint: 'Airflow & dbt, Kafka & Flink, watermarks, change data capture, and the Lambda-vs-Kappa religious war.' },
  { id: 'scale', label: '04 · at scale', title: 'What separates IC4 from IC5.',
    hint: 'Idempotency. Backfills. Effectively-exactly-once. Observability that catches the silent-failure modes. The interview itself.' },
];

window.LESSONS = [
  // TRACK 1 — FOUNDATIONS
  { id: 'mental-model', n: 1, track: 'foundations',
    title: 'The Stack, Top to Bottom',
    sub: 'Source → log → lake → warehouse → mart',
    hook: 'Where bytes live, why they live there, and what each layer is actually for.',
    file: 'lessons/01-mental-model.html',
    time: '12 min', interactives: 4 },
  { id: 'cap-pacelc', n: 2, track: 'foundations',
    title: 'CAP, PACELC & The Latency Tax',
    sub: 'The two impossibility theorems',
    hook: 'You can\'t have all three. What you trade for what — and the question CAP forgot to ask.',
    file: 'lessons/02-cap-pacelc.html',
    time: '14 min', interactives: 4 },
  { id: 'modeling', n: 3, track: 'foundations',
    title: 'Modeling: OLTP vs OLAP vs Stream',
    sub: '3NF · Kimball · Wide-table · Vault',
    hook: 'Five modeling philosophies. When each one is right. When each one ruins your life.',
    file: 'lessons/03-modeling.html',
    time: '13 min', interactives: 3 },

  // TRACK 2 — STORAGE
  { id: 'storage-formats', n: 4, track: 'storage',
    title: 'Row vs Column: Inside Parquet',
    sub: 'Encodings · row groups · pushdown',
    hook: 'Why columnar wins for analytics. A Parquet file, dissected byte-by-byte.',
    file: 'lessons/04-storage-formats.html',
    time: '13 min', interactives: 4 },
  { id: 'lakehouse', n: 5, track: 'storage',
    title: 'The Lakehouse: Iceberg, Delta, Hudi',
    sub: 'ACID on object storage',
    hook: 'Snapshots, manifests, copy-on-write vs merge-on-read. The format war, ranked.',
    file: 'lessons/05-lakehouse.html',
    time: '15 min', interactives: 4 },
  { id: 'partitioning', n: 6, track: 'storage',
    title: 'Partitioning, Clustering, Small Files',
    sub: 'Lay out a petabyte to query a megabyte',
    hook: 'How partition keys, clustering, and Z-ordering turn full scans into tiny ones.',
    file: 'lessons/06-partitioning.html',
    time: '12 min', interactives: 3 },

  // TRACK 3 — MOVEMENT
  { id: 'batch-elt', n: 7, track: 'movement',
    title: 'Batch ETL & Orchestration',
    sub: 'Airflow · dbt · idempotent merges',
    hook: 'DAGs, retries, atomic publishing. The boring parts that pay the bills.',
    file: 'lessons/07-batch-elt.html',
    time: '13 min', interactives: 3 },
  { id: 'streaming', n: 8, track: 'movement',
    title: 'Streaming: Kafka, Watermarks, Windows',
    sub: 'Partitions · groups · event time',
    hook: 'Why event time ≠ processing time, and how watermarks let you reason about late data.',
    file: 'lessons/08-streaming.html',
    time: '15 min', interactives: 4 },
  { id: 'cdc-lambda-kappa', n: 9, track: 'movement',
    title: 'CDC, Lambda & Kappa',
    sub: 'Change data capture · two architectures',
    hook: 'How operational DBs become analytical streams — and which architecture is winning in 2026.',
    file: 'lessons/09-cdc-lambda-kappa.html',
    time: '14 min', interactives: 3 },

  // TRACK 4 — AT SCALE
  { id: 'idempotency', n: 10, track: 'scale',
    title: 'Idempotency, Backfills & Exactly-Once',
    sub: '"Effectively exactly-once."',
    hook: 'The phrase that separates IC4 from IC5. And the dead-letter queue that proves you mean it.',
    file: 'lessons/10-idempotency.html',
    time: '14 min', interactives: 3 },
  { id: 'sla-quality', n: 11, track: 'scale',
    title: 'SLAs, Observability & Data Quality',
    sub: 'Freshness · volume · drift · lineage',
    hook: 'Five layers of monitoring. What to alert on. What to ignore. How to never debug at 2am again.',
    file: 'lessons/11-sla-quality.html',
    time: '16 min', interactives: 3 },
  { id: 'interview-playbook', n: 12, track: 'scale',
    title: 'The IC5 Interview, Live',
    sub: 'Design a real-time seller analytics platform · 45 min',
    hook: 'A complete IC5 system design walkthrough — clarification, math, design, deep dives, scoring.',
    file: 'lessons/12-interview-playbook.html',
    time: '20 min', interactives: 4 },
];
