// Lesson catalogue — single source of truth
window.LESSONS = [
  {
    id: 'mental-model',
    num: '01',
    title: 'What Claude Actually Is',
    subtitle: 'A useful mental model before you type a single prompt.',
    track: 'Foundations',
    minutes: 8,
    file: 'lessons/01-mental-model.html',
    hook: 'Claude is not a search engine. It is not a database. It is something stranger and more useful.',
  },
  {
    id: 'anatomy',
    num: '02',
    title: 'Anatomy of a Great Prompt',
    subtitle: 'The Boris template: role, context, task, constraints, format.',
    track: 'Foundations',
    minutes: 12,
    file: 'lessons/02-anatomy.html',
    hook: 'Great prompts are not clever. They are structured.',
  },
  {
    id: 'context',
    num: '03',
    title: 'Context Windows & Semantic Models',
    subtitle: 'How Claude "sees" your text — and why token order matters.',
    track: 'Foundations',
    minutes: 10,
    file: 'lessons/03-context.html',
    hook: 'Meaning is geometry. Let\'s look at the map.',
  },
  {
    id: 'claude-md',
    num: '04',
    title: 'The CLAUDE.md File',
    subtitle: 'Persistent instructions that travel with your project.',
    track: 'Workflows',
    minutes: 9,
    file: 'lessons/04-claude-md.html',
    hook: 'Write it once. Never re-explain your stack again.',
  },
  {
    id: 'iteration',
    num: '05',
    title: 'Iterative Prompting',
    subtitle: 'Why the second prompt is always better — and how to get there in fewer tries.',
    track: 'Workflows',
    minutes: 10,
    file: 'lessons/05-iteration.html',
    hook: 'First drafts are for calibration, not delivery.',
  },
  {
    id: 'gdocs',
    num: '06',
    title: 'Claude for Perfect Google Docs',
    subtitle: 'From bullet dump to crisp doc in under five minutes.',
    track: 'Workflows',
    minutes: 8,
    file: 'lessons/06-gdocs.html',
    hook: 'The doc is the artifact. The prompt is the mold.',
  },
  {
    id: 'agents',
    num: '07',
    title: 'Agentic Workflows & Tool Use',
    subtitle: 'When Claude stops answering and starts doing.',
    track: 'Advanced',
    minutes: 11,
    file: 'lessons/07-agents.html',
    hook: 'Agents are loops. Loops need guardrails.',
  },
  {
    id: 'reviews',
    num: '08',
    title: 'Claude for Code Review & PRs',
    subtitle: 'Your tireless, slightly-pedantic reviewer.',
    track: 'Advanced',
    minutes: 9,
    file: 'lessons/08-reviews.html',
    hook: 'Claude reads diffs. It reads subtext, too.',
  },
  {
    id: 'grounding',
    num: '09',
    title: 'Avoiding Hallucinations',
    subtitle: 'Ground the model in your data, or prepare for fiction.',
    track: 'Advanced',
    minutes: 10,
    file: 'lessons/09-grounding.html',
    hook: 'If it isn\'t in context, it isn\'t knowledge.',
  },
  {
    id: 'team',
    num: '10',
    title: 'Team Workflows',
    subtitle: 'Shared prompts, shared CLAUDE.md, shared gains.',
    track: 'Team',
    minutes: 10,
    file: 'lessons/10-team.html',
    hook: 'One person\'s breakthrough is everybody\'s baseline.',
  },
  {
    id: 'evals',
    num: '11',
    title: 'Prompt Debugging & Evals',
    subtitle: 'How to know a prompt is actually better.',
    track: 'Team',
    minutes: 12,
    file: 'lessons/11-evals.html',
    hook: 'Vibes are not a measurement.',
  },
  {
    id: 'safety',
    num: '12',
    title: 'Safety, Privacy & What Not To Paste',
    subtitle: 'The short list of things that never go in a prompt.',
    track: 'Team',
    minutes: 8,
    file: 'lessons/12-safety.html',
    hook: 'Treat the prompt box like the address bar of the internet.',
  },
];

window.TRACKS = [
  { id: 'Foundations', label: 'Foundations', hint: 'Start here. Mental model + the craft of prompting.' },
  { id: 'Workflows', label: 'Everyday workflows', hint: 'Where Claude saves you hours every week.' },
  { id: 'Advanced', label: 'Going deeper', hint: 'Agents, code review, grounding against hallucinations.' },
  { id: 'Team', label: 'Team & rigor', hint: 'Share it safely, measure it honestly.' },
];
